export const API_CONSTANTS = {
  USER_LOGIN: "USER_LOGIN",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",

  USER_LOGIN_FAILED: "USER_LOGIN_FAILED",

  USER_PROFILE: "USER_PROFILE",
  USER_PROFILE_SUCCESS: "USER_PROFILE_SUCCESS",

  CREATE_USER: "CREATE_USER",
  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",

  UPLOAD_SCANNED_FILES: "UPLOAD_SCANNED_FILES",
  UPLOAD_SCANNED_FILES_SUCCESS: "UPLOAD_SCANNED_FILES_SUCCESS",

  ALLOCATE_TO_RECTIFY: "ALLOCATE_TO_RECTIFY",
  ALLOCATE_TO_RECTIFY_SUCCESS: "ALLOCATE_TO_RECTIFY_SUCCESS",

  ALLOCATE_TO_DIGITIZE: "ALLOCATE_TO_DIGITIZE",
  ALLOCATE_TO_DIGITIZE_SUCCESS: "ALLOCATE_TO_DIGITIZE_SUCCESS",

  ALLOCATE_TO_SHAPE: "ALLOCATE_TO_SHAPE",
  ALLOCATE_TO_SHAPE_SUCCESS: "ALLOCATE_TO_SHAPE_SUCCESS",

  ALLOCATE_TO_RECTIFY_AGENCY: "ALLOCATE_TO_RECTIFY_AGENCY",
  ALLOCATE_TO_RECTIFY_AGENCY_SUCCESS: "ALLOCATE_TO_RECTIFY_AGENCY_SUCCESS",

  SET_UPLOAD_DIGITIZED_FILES_BY_USER_FALSE:
    "SET_UPLOAD_DIGITIZED_FILES_BY_USER_FALSE",

    SET_UPLOAD_SHAPE_FILES_BY_USER_FALSE:
    "SET_UPLOAD_SHAPE_FILES_BY_USER_FALSE",

  SET_UPLOAD_TOPOLOGY_FILES_BY_USER_FALSE:
    "SET_UPLOAD_TOPOLOGY_FILES_BY_USER_FALSE",

  ALLOCATE_TO_RECTIFY_PUT: "ALLOCATE_TO_RECTIFY_PUT",
  ALLOCATE_TO_RECTIFY_PUT_SUCCESS: "ALLOCATE_TO_RECTIFY_PUT_SUCCESS",

  ALLOCATE_TO_DIGITIZE_AGENCY: "ALLOCATE_TO_DIGITIZE_AGENCY",
  ALLOCATE_TO_DIGITIZE_AGENCY_SUCCESS: "ALLOCATE_TO_DIGITIZE_AGENCY_SUCCESS",

  
  ALLOCATE_TO_SHAPE_AGENCY: "ALLOCATE_TO_SHAPE_AGENCY",
  ALLOCATE_TO_SHAPE_AGENCY_SUCCESS: "ALLOCATE_TO_SHAPE_AGENCY_SUCCESS",

  ALLOCATE_TO_TOPOLOGY_AGENCY: "ALLOCATE_TO_TOPOLOGY_AGENCY",
  ALLOCATE_TO_TOPOLOGY_AGENCY_SUCCESS: "ALLOCATE_TO_TOPOLOGY_AGENCY_SUCCESS",

  UPLOAD_RECTIFY_FILES: "UPLOAD_RECTIFY_FILES",
  UPLOAD_RECTIFY_FILES_SUCCESS: "UPLOAD_RECTIFY_FILES_SUCCESS",

  UPLOAD_RECTIFY_FILES_REJECTED: "UPLOAD_RECTIFY_FILES_REJECTED",
  UPLOAD_RECTIFY_FILES_REJECTED_SUCCESS:
    "UPLOAD_RECTIFY_FILES_REJECTED_SUCCESS",

  UPLOAD_DIGITIZED_FILES: "UPLOAD_DIGITIZED_FILES",
  UPLOAD_DIGITIZED_FILES_SUCCESS: "UPLOAD_DIGITIZED_FILES_SUCCESS",

  UPLOAD_SHAPE_FILES: "UPLOAD_SHAPE_FILES",
  UPLOAD_SHAPE_FILES_SUCCESS: "UPLOAD_SHAPE_FILES_SUCCESS",

  UPLOAD_TOPOLOGY_FILES: "UPLOAD_TOPOLOGY_FILES",
  UPLOAD_TOPOLOGY_FILES_SUCCESS: "UPLOAD_TOPOLOGY_FILES_SUCCESS",

  UPLOAD_QC_FILES: "UPLOAD_QC_FILES",
  UPLOAD_QC_FILES_SUCCESS: "UPLOAD_QC_FILES_SUCCESS",

  UPLOAD_GOV_QC_FILES: "UPLOAD_GOV_QC_FILES",
  UPLOAD_GOV_QC_FILES_SUCCESS: "UPLOAD_GOV_QC_FILES_SUCCESS",

  //pagination
  GET_PAGINATION_DETAILS: "GET_PAGINATION_DETAILS",
  GET_PAGINATION_DETAILS_SUCCESS: "GET_PAGINATION_DETAILS_SUCCESS",

  GET_DIGITIZE_PAGINATION_DETAILS: "GET_DIGITIZE_PAGINATION_DETAILS",
  GET_DIGITIZE_PAGINATION_DETAILS_SUCCESS:
    "GET_DIGITIZE_PAGINATION_DETAILS_SUCCESS",

  GET_SHAPE_PAGINATION_DETAILS: "GET_SHAPE_PAGINATION_DETAILS",
  GET_SHAPE_PAGINATION_DETAILS_SUCCESS: "GET_SHAPE_PAGINATION_DETAILS_SUCCESS",

  GET_GOV_QC_PDF_DOC_LIST_PAGINATION_DETAILS: "GET_GOV_QC_PDF_DOC_LIST_PAGINATION_DETAILS",
  GET_GOV_QC_PDF_DOC_LIST_PAGINATION_DETAILS_SUCCESS: "GET_GOV_QC_PDF_DOC_LIST_PAGINATION_DETAILS_SUCCESS",

  // agency listing
  AGENCY_LISTING: "AGENCY_LISTING",
  AGENCY_LISTING_SUCCESS: "AGENCY_LISTING_SUCCESS",

  AGENCY_USER_LIST: "AGENCY_USER_LIST",
  AGENCY_USER_LIST_SUCCESS: "AGENCY_USER_LIST_SUCCESS",

  // all users list
  ALL_USERS_LIST: "ALL_USERS_LIST",
  ALL_USERS_LIST_SUCCESS: "ALL_USERS_LIST_SUCCESS",

  // rectify agency action
  GET_RECTIFY_AGENCY_ACTION: "RECTIFY_AGENCY_ACTION",
  GET_RECTIFY_AGENCY_ACTION_SUCCESS: "RECTIFY_AGENCY_ACTION_SUCCESS",

  // user table retify action
  GET_USER_RECTIFY_ACTION: "GET_USER_RECTIFY_ACTION",
  GET_USER_RECTIFY_ACTION_SUCCESS: "GET_USER_RECTIFY_ACTION_SUCCESS",

  //allocate the scaned files to the user by agency
  ALLOCATE_TO_USER: "ALLOCATE_TO_USER",
  ALLOCATE_TO_USER_SUCCESS: "ALLOCATE_TO_USER_SUCCESS",

  SUBMIT_TO_AGENCY: "SUBMIT_TO_AGENCY",
  SUBMIT_TO_AGENCY_SUCCESS: "SUBMIT_TO_AGENCY_SUCCESS",

  SHAPE_SUBMIT_TO_AGENCY: "SHAPE_SUBMIT_TO_AGENCY",
  SHAPE_SUBMIT_TO_AGENCY_SUCCESS: "SHAPE_SUBMIT_TO_AGENCY_SUCCESS",

  TOPOLOGY_SUBMIT_TO_AGENCY: "TOPOLOGY_SUBMIT_TO_AGENCY",
  TOPOLOGY_SUBMIT_TO_AGENCY_SUCCESS: "TOPOLOGY_SUBMIT_TO_AGENCY_SUCCESS",

  // get users scan upload files
  GET_USERS_SCAN_UPLOAD_FILES: "GET_USERS_SCAN_UPLOAD_FILES",
  GET_USERS_SCAN_UPLOAD_FILES_SUCCESS: "GET_USERS_SCAN_UPLOAD_FILES_SUCCESS",

  ALLOCATE_DIGITIZE_FILES_TO_USER: "ALLOCATE_DIGITIZE_FILES_TO_USER",
  ALLOCATE_DIGITIZE_FILES_TO_USER_SUCCESS:
    "ALLOCATE_DIGITIZE_FILES_TO_USER_SUCCESS",

  ALLOCATE_SHAPE_FILES_TO_USER: "ALLOCATE_SHAPE_FILES_TO_USER",
  ALLOCATE_SHAPE_FILES_TO_USER_SUCCESS:
    "ALLOCATE_SHAPE_FILES_TO_USER_SUCCESS",

  ALLOCATE_TOPOLOGY_FILES_TO_USER: "ALLOCATE_TOPOLOGY_FILES_TO_USER",
  ALLOCATE_TOPOLOGY_FILES_TO_USER_SUCCESS:
    "ALLOCATE_TOPOLOGY_FILES_TO_USER_SUCCESS",

  DIGITIZE_AGENCY_PAGINATION_ACTION: "DIGITIZE_AGENCY_PAGINATION_ACTION",
  DIGITIZE_AGENCY_PAGINATION_ACTION_SUCCESS:
    "DIGITIZE_AGENCY_PAGINATION_ACTION_SUCCESS",

  SHAPE_AGENCY_PAGINATION_ACTION: "SHAPE_AGENCY_PAGINATION_ACTION",
  SHAPE_AGENCY_PAGINATION_ACTION_SUCCESS:
      "SHAPE_AGENCY_PAGINATION_ACTION_SUCCESS",

  TOPOLOGY_AGENCY_PAGINATION_ACTION: "TOPOLOGY_AGENCY_PAGINATION_ACTION",
  TOPOLOGY_AGENCY_PAGINATION_ACTION_SUCCESS: "TOPOLOGY_AGENCY_PAGINATION_ACTION_SUCCESS",

  DIGITIZATION_PROCESS_USER: "DIGITIZATION_PROCESS_USER",
  DIGITIZATION_PROCESS_USER_SUCCESS: "DIGITIZATION_PROCESS_USER_SUCCESS",

  SHAPE_PROCESS_USER: "SHAPE_PROCESS_USER",
  SHAPE_PROCESS_USER_SUCCESS: "SHAPE_PROCESS_USER_SUCCESS",

  TOPOLOGY_PROCESS_USER: "TOPOLOGY_PROCESS_USER",
  TOPOLOGY_PROCESS_USER_SUCCESS: "TOPOLOGY_PROCESS_USER_SUCCESS",

  USER_PAGINATION_DIGITIZE_ACTION: "USER_PAGINATION_DIGITIZE_ACTION",
  USER_PAGINATION_DIGITIZE_ACTION_SUCCESS:
    "USER_PAGINATION_DIGITIZE_ACTION_SUCCESS",

  USER_PAGINATION_SHAPE_ACTION: "USER_PAGINATION_SHAPE_ACTION",
  USER_PAGINATION_SHAPE_ACTION_SUCCESS:
    "USER_PAGINATION_SHAPE_ACTION_SUCCESS",

  USER_PAGINATION_TOPOLOGY_ACTION: "USER_PAGINATION_TOPOLOGY_ACTION",
  USER_PAGINATION_TOPOLOGY_ACTION_SUCCESS:
    "USER_PAGINATION_TOPOLOGY_ACTION_SUCCESS",

  UPLOAD_DIGITIZED_FILES_BY_USER: "UPLOAD_DIGITIZED_FILES_BY_USER",
  UPLOAD_DIGITIZED_FILES_BY_USER_SUCCESS:
    "UPLOAD_DIGITIZED_FILES_BY_USER_SUCCESS",

  UPLOAD_SHAPE_FILES_BY_USER: "UPLOAD_SHAPE_FILES_BY_USER",
  UPLOAD_SHAPE_FILES_BY_USER_SUCCESS:
    "UPLOAD_SHAPE_FILES_BY_USER_SUCCESS",

  UPLOAD_TOPOLOGY_FILES_BY_USER: "UPLOAD_TOPOLOGY_FILES_BY_USER",
  UPLOAD_TOPOLOGY_FILES_BY_USER_SUCCESS:
    "UPLOAD_TOPOLOGY_FILES_BY_USER_SUCCESS",

  UPLOAD_DIGITIZED_FILES_BY_USER_REJECTED:
    "UPLOAD_DIGITIZED_FILES_BY_USER_REJECTED",

  UPLOAD_DIGITIZED_FILES_BY_USER_REJECTED_SUCCESS:
    "UPLOAD_DIGITIZED_FILES_BY_USER_REJECTED_SUCCESS",

  UPLOAD_SHAPE_FILES_BY_USER_REJECTED:
    "UPLOAD_SHAPE_FILES_BY_USER_REJECTED",

  UPLOAD_SHAPE_FILES_BY_USER_REJECTED_SUCCESS:
    "UPLOAD_SHAPE_FILES_BY_USER_REJECTED_SUCCESS",

  UPLOAD_TOPOLOGY_FILES_BY_USER_REJECTED:
    "UPLOAD_TOPOLOGY_FILES_BY_USER_REJECTED",

  UPLOAD_TOPOLOGY_FILES_BY_USER_REJECTED_SUCCESS:
    "UPLOAD_TOPOLOGY_FILES_BY_USER_REJECTED_SUCCESS",

  GET_QC_DETAILS: "GET_QC_DETAILS",
  GET_QC_DETAILS_SUCCESS: "GET_QC_DETAILS_SUCCESS",

  QC_DETAILS_PAGINATION: "QC_DETAILS_PAGINATION",
  QC_DETAILS_PAGINATION_SUCCESS: "QC_DETAILS_PAGINATION_SUCCESS",

  ALLOCATE_QC_FILES_TO_AGENCY: "ALLOCATE_QC_FILES_TO_AGENCY",
  ALLOCATE_QC_FILES_TO_AGENCY_SUCCESS: "ALLOCATE_QC_FILES_TO_AGENCY_SUCCESS",

  GET_QC_FILE_AGENCY_ADMIN: "GET_QC_FILE_AGENCY_ADMIN",
  GET_QC_FILE_AGENCY_ADMIN_SUCCESS: "GET_QC_FILE_AGENCY_ADMIN_SUCCESS",

  ASSIGN_QC_FILES_TO_USER: "ASSIGN_QC_FILES_TO_USER",
  ASSIGN_QC_FILES_TO_USER_SUCCESS: "ASSIGN_QC_FILES_TO_USER_SUCCESS",

  QC_AGENCY_PAGINATION_ACTION: "QC_AGENCY_PAGINATION_ACTION",
  QC_AGENCY_PAGINATION_ACTION_SUCCESS: "QC_AGENCY_PAGINATION_ACTION_SUCCESS",

  GET_GOVT_QC_FILE_DIST_ADMIN: "GET_GOVT_QC_FILE_DIST_ADMIN",
  GET_GOVT_QC_FILE_DIST_ADMIN_SUCCESS: "GET_GOVT_QC_FILE_DIST_ADMIN_SUCCESS",

  GOVT_QC_PAGINATION_DIST_ADMIN_ACTION: "GOVT_QC_PAGINATION_DIST_ADMIN_ACTION",
  GOVT_QC_PAGINATION_DIST_ADMIN_ACTION_SUCCESS:
    "GOVT_QC_PAGINATION_DIST_ADMIN_ACTION_SUCCESS",

  ALLOCATE_PDF_FILES_TO_DIST_ADMIN: "ALLOCATE_PDF_FILES_TO_DIST_ADMIN",
  ALLOCATE_PDF_FILES_TO_DIST_ADMIN_SUCCESS:
    "ALLOCATE_PDF_FILES_TO_DIST_ADMIN_SUCCESS",

  ALLOCATE_DIGITIZED_FILES_TO_USER: "ALLOCATE_DIGITIZED_FILES_TO_USER",
  ALLOCATE_DIGITIZED_FILES_TO_USER_SUCCESS:
    "ALLOCATE_DIGITIZED_FILES_TO_USER_SUCCESS",

  GET_QC_FILES_TO_USER: "GET_QC_FILES_TO_USER",
  GET_QC_FILES_TO_USER_SUCCESS: "GET_QC_FILES_TO_USER_SUCCESS",

  USER_QC_PAGINATION: "USER_QC_PAGINATION",
  USER_QC_PAGINATION_SUCCESS: "USER_QC_PAGINATION_SUCCESS",

  GET_PDF_FILES_TO_USER: "GET_PDF_FILES_TO_USER",
  GET_PDF_FILES_TO_USER_SUCCESS: "GET_PDF_FILES_TO_USER_SUCCESS",

  USER_PDF_PAGINATION: "USER_PDF_PAGINATION",
  USER_PDF_PAGINATION_SUCCESS: "USER_PDF_PAGINATION_SUCCESS",

  UPLOAD_QC_FILES_USER: "UPLOAD_QC_FILES_USER",
  UPLOAD_QC_FILES_USER_SUCCESS: "UPLOAD_QC_FILES_USER_SUCCESS",

  UPLOAD_QC_FILES_REJECTED: "UPLOAD_QC_FILES_REJECTED",
  UPLOAD_QC_FILES_REJECTED_SUCCESS: "UPLOAD_QC_FILES_REJECTED_SUCCESS",

  UPDATE_POLYGON_COUNT: "UPDATE_POLYGON_COUNT",
  UPDATE_POLYGON_COUNT_SUCCESS: "UPDATE_POLYGON_COUNT_SUCCESS",

  ADD_AGENCY_USER: "ADD_AGENCY_USER",
  ADD_AGENCY_USER_SUCCESS: "ADD_AGENCY_USER_SUCCESS",

  GET_ALL_DOCUMENT_LIST_SUPER_AND_ADMIN:
    "GET_ALL_DOCUMENT_LIST_SUPER_AND_ADMIN",
  GET_ALL_DOCUMENT_LIST_SUPER_AND_ADMIN_SUCCESS:
    "GET_ALL_DOCUMENT_LIST_SUPER_AND_ADMIN_SUCCESS",

  ALL_DOCUMENT_PAGINATION_ACTION_SUPER_ADMIN:
    "ALL_DOCUMENT_PAGINATION_ACTION_SUPER_ADMIN",
  ALL_DOCUMENT_PAGINATION_ACTION_SUPER_ADMIN_SUCCESS:
    "ALL_DOCUMENT_PAGINATION_ACTION_SUPER_ADMIN_SUCCESS",

  GET_DASHBOARD_DETAILS: "GET_DASHBOARD_DETAILS",
  GET_DASHBOARD_DETAILS_SUCCESS: "GET_DASHBOARD_DETAILS_SUCCESS",

  GET_DEPARTMENT_LIST: "GET_DEPARTMENT_LIST",
  GET_DEPARTMENT_LIST_SUCCESS: "GET_DEPARTMENT_LIST_SUCCESS",

  DIGITIZE_AGENCY_USER_LIST: "DIGITIZE_AGENCY_USER_LIST",
  DIGITIZE_AGENCY_USER_LIST_SUCCESS: "DIGITIZE_AGENCY_USER_LIST_SUCCESS",

  SHAPE_AGENCY_USER_LIST: "SHAPE_AGENCY_USER_LIST",
  SHAPE_AGENCY_USER_LIST_SUCCESS: "SHAPE_AGENCY_USER_LIST_SUCCESS",

  TOPOLOGY_AGENCY_USER_LIST: "TOPOLOGY_AGENCY_USER_LIST",
  TOPOLOGY_AGENCY_USER_LIST_SUCCESS: "TOPOLOGY_AGENCY_USER_LIST_SUCCESS",

  QC_AGENCY_USER_LIST: "QC_AGENCY_USER_LIST",
  QC_AGENCY_USER_LIST_SUCCESS: "QC_AGENCY_USER_LIST_SUCCESS",
  SET_UPLOADING_FALSE: "SET_UPLOADING_FALSE",

  DISTRICT_USER_LIST: "DISTRICT_USER_LIST",
  DISTRICT_USER_LIST_SUCCESS: "DISTRICT_USER_LIST_SUCCESS",

  GET_GOVT_QC_PDF_COMPLETE_DOC_LIST: "GET_GOVT_QC_PDF_COMPLETE_DOC_LIST",
  GET_GOVT_QC_PDF_COMPLETE_DOC_LIST_SUCCESS: "GET_GOVT_QC_PDF_COMPLETE_DOC_LIST_SUCCESS",

  GET_AGENCY_LISTING: "GET_AGENCY_LISTING",
  GET_AGENCY_LISTING_SUCCESS: "GET_AGENCY_LISTING_SUCCESS",

  USER_WISE_DOCUMENT_COUNT: "USER_WISE_DOCUMENT_COUNT",
  USER_WISE_DOCUMENT_COUNT_SUCCESS: "USER_WISE_DOCUMENT_COUNT_SUCCESS",

  AGENCY_USER_DETAILS_COUNT: "AGENCY_USER_DETAILS_COUNT",
  AGENCY_USER_DETAILS_COUNT_SUCCESS: "AGENCY_USER_DETAILS_COUNT_SUCCESS",

  CREATE_AGENCY: "CREATE_AGENCY",
  CREATE_AGENCY_SUCCESS: "CREATE_AGENCY_SUCCESS",

  SET_AGENCY_CREATION_FORM_SUBMISSION_RESULT:
    "SET_AGENCY_CREATION_FORM_SUBMISSION_RESULT",

  SET_USER_CREATION_FORM_SUBMISSION_RESULT:
    "SET_USER_CREATION_FORM_SUBMISSION_RESULT",

  GET_NOT_FOUND_DOCUMENTS_LIST: "GET_NOT_FOUND_DOCUMENTS_LIST",
  GET_NOT_FOUND_DOCUMENTS_LIST_SUCCESS: "GET_NOT_FOUND_DOCUMENTS_LIST_SUCCESS",

  GET_NOT_FOUND_DOCUMENTS_PAGINATION_LIST:
    "GET_NOT_FOUND_DOCUMENTS_PAGINATION_LIST",
  GET_NOT_FOUND_DOCUMENTS_PAGINATION_LIST_SUCCESS:
    "GET_NOT_FOUND_DOCUMENTS_PAGINATION_LIST_SUCCESS",

  CREATE_AGENCY_AND_ADMIN: "CREATE_AGENCY_AND_ADMIN",
  CREATE_AGENCY_AND_ADMIN_SUCCESS: "CREATE_AGENCY_AND_ADMIN_SUCCESS",

  SET_CREATE_AGENCY_AND_ADMIN_FALSE: "SET_CREATE_AGENCY_AND_ADMIN_FALSE",

  GET_DISTRICT_WISE_DOCUMENT_LIST: "GET_DISTRICT_WISE_DOCUMENT_LIST",
  GET_DISTRICT_WISE_DOCUMENT_LIST_SUCCESS:
    "GET_DISTRICT_WISE_DOCUMENT_LIST_SUCCESS",

  DOWNLOAD_EXCEL_FILE: "DOWNLOAD_EXCEL_FILE",
  DOWNLOAD_EXCEL_FILE_SUCCESS: "DOWNLOAD_EXCEL_FILE_SUCCESS",

  CREATE_DISTRICT_FORM: "CREATE_DISTRICT_FORM",
  CREATE_DISTRICT_FORM_SUCCESS: "CREATE_DISTRICT_FORM_SUCCESS",

  SET_CREATE_CREATE_DISTRICT_FALSE: "SET_CREATE_CREATE_DISTRICT_FALSE",

  CREATE_VILLAGE_FORM: "CREATE_VILLAGE_FORM",
  CREATE_VILLAGE_FORM_SUCCESS: "CREATE_VILLAGE_FORM_SUCCESS",

  SET_CREATE_VILLAGE_FALSE: "SET_CREATE_VILLAGE_FALSE",

  CREATE_TALUKA_FORM: "CREATE_TALUKA_FORM",
  CREATE_TALUKA_FORM_SUCCESS: "CREATE_TALUKA_FORM_SUCCESS",

  GET_DISTRICT_LIST: "GET_DISTRICT_LIST",
  GET_DISTRICT_LIST_SUCCESS: "GET_DISTRICT_LIST_SUCCESS",

  SET_TALUKA_RESULT_FALSE: "SET_TALUKA_RESULT_FALSE",

  GET_TALUKA_LIST: "GET_TALUKA_LIST",
  GET_TALUKA_LIST_SUCCESS: "GET_TALUKA_LIST_SUCCESS",

  SET_CREATE_TALUKS_FALSE: "SET_CREATE_TALUKS_FALSE",
  SET_VILLAGE_LIST_FALSE: "SET_VILLAGE_LIST_FALSE",

  SET_LOADING_TRUE: "SET_LOADING_TRUE",
  SET_LOADING_FALSE: "SET_LOADING_FALSE",

  MAP_TYPE_DOCUMET_LIST_COUNT: "MAP_TYPE_DOCUMET_LIST_COUNT",
  MAP_TYPE_DOCUMET_LIST_COUNT_SUCCESS: "MAP_TYPE_DOCUMET_LIST_COUNT_SUCCESS",

  FILETER_MAP_TYPE_BY_VILLAGE: "FILETER_MAP_TYPE_BY_VILLAGE",
  FILETER_MAP_TYPE_BY_VILLAGE_SUCCESS: "FILETER_MAP_TYPE_BY_VILLAGE_SUCCESS",

  USER_LIST_PAGEINATION: "USER_LIST_PAGEINATION",
  USER_LIST_PAGEINATION_SUCCESS: "USER_LIST_PAGEINATION_SUCCESS",

  SET_DOWNLOAD_EXCEL_FILE_FALSE: "SET_DOWNLOAD_EXCEL_FILE_FALSE",

  GET_VILLAGE_LIST: "GET_VILLAGE_LIST",
  GET_VILLAGE_LIST_SUCCESS: "GET_VILLAGE_LIST_SUCCESS",

  SET_VILLAGE_LIST_MAP_FLASSE: "SET_VILLAGE_LIST_MAP_FLASSE",

  SET_TALUKA_LIST_MAP_TYPE_FALSE: "SET_TALUKA_LIST_MAP_TYPE_FALSE ",

  GET_TALUKS_LIST_MAP_TYPE: "GET_TALUKS_LIST_MAP_TYPE",
  GET_TALUKS_LIST_MAP_TYPE_SUCCESS: "GET_TALUKS_LIST_MAP_TYPE_SUCCESS",
  SET_TALUKA_LIST_MAP_TPYE_FALSE: "SET_TALUKA_LIST_MAP_TPYE_FALSE",

  GET_TALUKA_MAP_TYPE_LIST_RECORDS: "GET_TALUKA_MAP_TYPE_LIST_RECORDS",
  GET_TALUKA_MAP_TYPE_LIST_RECORDS_SUCCESS:
    "GET_TALUKA_MAP_TYPE_LIST_RECORDS_SUCCESS",

  GET_VILLAGE_MAP_TYPE_LIST_RECORDS: "GET_VILLAGE_MAP_TYPE_LIST_RECORDS",
  GET_VILLAGE_MAP_TYPE_LIST_RECORDS_SUCCESS:
    "GET_VILLAGE_MAP_TYPE_LIST_RECORDS_SUCCESS",

  GET_VILLAGE_WISE_MAP_TYPE_COUNT: "GET_VILLAGE_WISE_MAP_TYPE_COUNT",
  GET_VILLAGE_WISE_MAP_TYPE_COUNT_SUCCESS:
    "GET_VILLAGE_WISE_MAP_TYPE_COUNT_SUCCESS",

  RE_UPLOAD_SCANNED_FILES: "RE_UPLOAD_SCANNED_FILES",
  RE_UPLOAD_SCANNED_FILES_SUCCESS: "RE_UPLOAD_SCANNED_FILES_SUCCESS",

  USER_WISE_DOCUMENT_COUNT_COUNT: "USER_WISE_DOCUMENT_COUNT_COUNT",
  USER_WISE_DOCUMENT_COUNT_COUNT_SUCCESS:
    "USER_WISE_DOCUMENT_COUNT_COUNT_SUCCESS",

  SET_VILLAGE_MAP_TYPE_TO_FALSE: "SET_VILLAGE_MAP_TYPE_TO_FALSE",

  UPDATE_AGENCY_USER: "UPDATE_AGENCY_USER",
  UPDATE_AGENCY_USER_SUCCESS: "UPDATE_AGENCY_USER_SUCCESS",

  USER_DETAILS_DOCUMENT_COUNT_PAGINATION:
    "USER_DETAILS_DOCUMENT_COUNT_PAGINATION",

  USER_DETAILS_DOCUMENT_COUNT_PAGINATION_SUCCESS:
    "USER_DETAILS_DOCUMENT_COUNT_PAGINATION_SUCCESS",

  CHANGE_PAGE_SIZE_ACTION: "CHANGE_PAGE_SIZE_ACTION",
  CHANGE_PAGE_SIZE_ACTION_SUCCESS: "CHANGE_PAGE_SIZE_ACTION_SUCCESS",

  AGENCY_WISE_DOCUMENT_COUNT: "AGENCY_WISE_DOCUMENT_COUNT",
  AGENCY_WISE_DOCUMENT_COUNT_SUCCESS: "AGENCY_WISE_DOCUMENT_COUNT_SUCCESS",

  CORRECT_NOT_FOUNT_SCAN_FILE: "CORRECT_NOT_FOUNT_SCAN_FILE_URL",
  CORRECT_NOT_FOUNT_SCAN_FILE_SUCCESS: "CORRECT_NOT_FOUNT_SCAN_FILE_SUCCESS",

  GET_DEPEARTMENT_LIST: "GET_DEPEARTMENT_LIST",
  GET_DEPEARTMENT_LIST_SUCCESS: "GET_DEPEARTMENT_LIST_SUCCESS",

  GET_FILE_EXCHANGE_USER_LIST: "GET_FILE_EXCHANGE_USER_LIST",
  GET_FILE_EXCHANGE_USER_LIST_SUCCESS: "GET_FILE_EXCHANGE_USER_LIST_SUCCESS",

  SET_USER_DEPARTMENT_LIST: "GET_FILE_EXCHANGE_USER_LIST",
  SET_USER_LIST_EMPTY: "SET_USER_LIST_EMPTY",
  SET_USER_LIST_EMPTY_SUCCESS: "SET_USER_LIST_EMPTY_SUCCESS",

  GET_SELECTED_USER_FILES: "GET_SELECTED_USER_FILES",
  GET_SELECTED_USER_FILES_SUCCESS: "GET_SELECTED_USER_FILES_SUCCESS",

  SET_USER_ALLOCATION_FEILD_FALSE: "SET_USER_ALLOCATION_FEILD_FALSE",

  GET_AGENCY_ALLOCATED_EXCHANGE_LIST: "GET_AGENCY_ALLOCATED_EXCHANGE_LIST",
  GET_AGENCY_ALLOCATED_EXCHANGE_LIST_SUCCESS:
    "GET_AGENCY_ALLOCATED_EXCHANGE_LIST_SUCCESS",

  GET_COMMON_TALUKA_DETAILS: "GET_COMMON_TALUKA_DETAILS",
  GET_COMMON_TALUKA_DETAILS_SUCCESS: "GET_COMMON_TALUKA_DETAILS_SUCCESS",

  GET_COMMON_DISTRICT_DETAILS: "GET_COMMON_DISTRICT_DETAILS",
  GET_COMMON_DISTRICT_DETAILS_SUCCESS: "GET_COMMON_DISTRICT_DETAILS_SUCCESS",

  POST_PRESCAN_DOCUMENT: "POST_PRESCAN_DOCUMENT",
  POST_PRESCAN_DOCUMENT_SUCCESS: "POST_PRESCAN_DOCUMENT_SUCCESS",

  SET_POST_PRESCAN_DOCUMENT_SUCCESS: "SET_POST_PRESCAN_DOCUMENT_SUCCESS",

  GET_POST_PRESCAN_DOCUMENT_LIST: "GET_POST_PRESCAN_DOCUMENT_LIST",
  GET_POST_PRESCAN_DOCUMENT_LIST_SUCCESS:
    "GET_POST_PRESCAN_DOCUMENT_LIST_SUCCESS",

  DIST_TALUKSWISE_PRESCANNING_DOCUMENT_LIST:
    "DIST_TALUKSWISE_PRESCANNING_DOCUMENT_LIST",

  DIST_TALUKSWISE_PRESCANNING_DOCUMENT_LIST_SUCCESS:
    "DIST_TALUKSWISE_PRESCANNING_DOCUMENT_LIST_SUCCESS",

  POST_BELL_EXCEL_FILE: "POST_BELL_EXCEL_FILE",
  POST_BELL_EXCEL_FILE_SUCCESS: "POST_BELL_EXCEL_FILE_SUCCESS",

  POST_BELL_EXCEL_FILE_FALSE: "POST_BELL_EXCEL_FILE_FALSE",

  GET_MAP_TYPE_LIST: "GET_MAP_TYPE_LIST",
  GET_MAP_TYPE_LIST_SUCCESS: "GET_MAP_TYPE_LIST_SUCCESS",

  GET_BARCODE_FROM_IMAGE: "GET_BARCODE_FROM_IMAGE",
  GET_BARCODE_FROM_IMAGE_SUCCESS: "GET_BARCODE_FROM_IMAGE_SUCCESS",

  UPDATE_BARCODE_NUMBER: "UPDATE_BARCODE_NUMBER",
  UPDATE_BARCODE_NUMBER_SUCCESS: "UPDATE_BARCODE_NUMBER_SUCCESS",

  SET_BARCODE_UPDATE_RESULT_FALSE: "SET_BARCODE_UPDATE_RESULT_FALSE",

  CREATE_TALUKA_ADMIN: "CREATE_TALUKA_ADMIN",
  CREATE_TALUKA_ADMIN_SUCCESS: "CREATE_TALUKA_ADMIN_SUCCESS",

  SET_CREATE_TALUKA_ADMIN_RESULT_FALSE: "SET_CREATE_TALUKA_ADMIN_RESULT_FALSE",
  CREATE_DISTRICT_ADMIN: "CREATE_DISTRICT_ADMIN",
  CREATE_DISTRICT_ADMIN_SUCCESS: "CREATE_DISTRICT_ADMIN_SUCCESS",
  SET_CREATE_DISTRICT_ADMIN_FALSE: "SET_CREATE_DISTRICT_ADMIN_FALSE",

  CREATE_PRE_DRAFT_REPORT: "CREATE_PRE_DRAFT_REPORT",
  CREATE_PRE_DRAFT_REPORT_SUCCESS: "CREATE_PRE_DRAFT_REPORT_SUCCESS",
  SET_CREATE_PRE_DRAFT_REPORT_FALSE: "SET_CREATE_PRE_DRAFT_REPORT_FALSE",

  PRE_DRAFT_DOCUMENT_LIST: "PRE_DRAFT_DOCUMENT_LIST_URL",
  PRE_DRAFT_DOCUMENT_LIST_SUCCESS: "PRE_DRAFT_DOCUMENT_LIST_URL_SUCCESS",

  PRE_DRAFT_SUB_DOCUMENT_LIST: "PRE_DRAFT_SUB_DOCUMENT_LIST",
  PRE_DRAFT_SUB_DOCUMENT_LIST_SUCCESS: "PRE_DRAFT_SUB_DOCUMENT_LIST_SUCCESS",

  SET_PAGINATION_COUNT_CHANGE_FALSE: "SET_PAGINATION_COUNT_CHANGE_FALSE",

  GET_TODAYS_MAP_TYPE_REPORT: "GET_TODAYS_MAP_TYPE_REPORT",
  GET_TODAYS_MAP_TYPE_REPORT_SUCCESS: "GET_TODAYS_MAP_TYPE_REPORT_SUCCESS",

  SET_DWG_FILE_UPLOADED_FALSE: "SET_DWG_FILE_UPLOADED_FALSE",
  SET_PDF_FILE_UPLOADED_FALSE: "SET_PDF_FILE_UPLOADED_FALSE",
  SET_QC_FILE_UPLOAD_FALSE: "SET_QC_FILE_UPLOAD_FALSE",
  SET_GOV_QC_FILE_UPLOADED_FALSE: "SET_GOV_QC_FILE_UPLOADED_FALSE",
  SET_GOV_PDF_FILE_UPLOADED_FALSE: "SET_GOV_PDF_FILE_UPLOADED_FALSE",

  UPLOAD_QC_FILES_USER_PDF: "UPLOAD_QC_FILES_USER_PDF",
  UPLOAD_QC_FILES_USER_PDF_SUCCESS: "UPLOAD_QC_FILES_USER_PDF_SUCCESS",

  GET_PRE_SCAN_DOCUMENT_LIST_ROW_SPAN: "GET_PRE_SCAN_DOCUMENT_LIST_ROW_SPAN",
  GET_PRE_SCAN_DOCUMENT_LIST_ROW_SPAN_SUCCESS:
    "GET_PRE_SCAN_DOCUMENT_LIST_ROW_SPAN_SUCCESS",

  GET_PRE_DRAFT_DOCUMENT_LIST_ROW_SPAN: "GET_PRE_DRAFT_DOCUMENT_LIST_ROW_SPAN",
  GET_PRE_DRAFT_DOCUMENT_LIST_ROW_SPAN_SUCCESS:
    "GET_PRE_DRAFT_DOCUMENT_LIST_ROW_SPAN_SUCCESS",

  GET_GOV_QC_FILES_TO_USER: "GET_GOV_QC_FILES_TO_USER",
  GET_GOV_QC_FILES_TO_USER_SUCCESS: "GET_GOV_QC_FILES_TO_USER_SUCCESS",

  USER_GOV_QC_PAGINATION: "USER_GOV_QC_PAGINATION",
  USER_GOV_QC_PAGINATION_SUCCESS: "USER_GOV_QC_PAGINATION_SUCCESS",

  UPLOAD_GOV_QC_FILES_USER: "UPLOAD_GOV_QC_FILES_USER",
  UPLOAD_GOV_QC_FILES_USER_SUCCESS: "UPLOAD_GOV_QC_FILES_USER_SUCCESS",

  GET_GOV_PDF_FILES_TO_USER: "GET_GOV_PDF_FILES_TO_USER",
  GET_GOV_PDF_FILES_TO_USER_SUCCESS: "GET_GOV_PDF_FILES_TO_USER_SUCCESS",

  USER_GOV_PDF_PAGINATION: "USER_GOV_PDF_PAGINATION",
  USER_GOV_PDF_PAGINATION_SUCCESS: "USER_GOV_PDF_PAGINATION_SUCCESS",

  UPLOAD_GOV_PDF_FILES_USER: "UPLOAD_GOV_PDF_FILES_USER",
  UPLOAD_GOV_PDF_FILES_USER_SUCCESS: "UPLOAD_GOV_PDF_FILES_USER_SUCCESS",

  UPDATE_POLYGON_QC_COUNT_RAW: "UPDATE_POLYGON_QC_COUNT_RAW",
  UPDATE_POLYGON_QC_COUNT_RAW_SUCCESS: "UPDATE_POLYGON_QC_COUNT_RAW_SUCCESS",

  SET_UPDATE_POLYGON_COUNT_FALSE: "SET_UPDATE_POLYGON_COUNT_FALSE",

  SET_ALLOCATE_TO_AGENCIES_RESULT_FALSE:
    "SET_ALLOCATE_TO_AGENCIES_RESULT_FALSE",

  RETRIEVE_FILE_FROM_AGENCY: "RETRIEVE_FILE_FROM_AGENCY",
  RETRIEVE_FILE_FROM_AGENCY_SUCCESS: "RETRIEVE_FILE_FROM_AGENCY_SUCCESS",

  RETRIEVE_FILE_FROM_AGENCY_FALSE: "RETRIEVE_FILE_FROM_AGENCY_FALSE",

  GET_FILES_FROM_AGENCY: "GET_FILES_FROM_AGENCY",
  GET_FILES_FROM_AGENCY_SUCCESS: "GET_FILES_FROM_AGENCY_SUCCESS",
  SET_GET_FILE_FROM_AGENCY_FALSE: "SET_GET_FILE_FROM_AGENCY_FALSE",

  DEACTIVATE_USER: "DEACTIVATE_USER",
  DEACTIVATE_USER_SUCCESS: "DEACTIVATE_USER_SUCCESS",

  QC_POLYGON_COUNT_UPDATE: "QC_POLYGON_COUNT_UPDATE",
  QC_POLYGON_COUNT_UPDATE_SUCCESS: "QC_POLYGON_COUNT_UPDATE_SUCCESS",
};
